---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-s2s-auth
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 51b92aab-bbf2-489e-b462-bf7bd547961b
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
          scope_resource_group_var_name: existing_resource_group_name
